language: ruby
sudo: false
cache: bundler
jdk: oraclejdk8

install:
- git clone https://github.com/graalvm/mx
- export PATH=$PWD/mx:$PATH
- git clone https://github.com/graalvm/truffleruby
- cd truffleruby
- echo MX_BINARY_SUITES=truffle >> mx.jruby/env
- echo JAVA_HOME=$JAVA_HOME >> mx.jruby/env
- mx build
- rvm mount $PWD -n truffleruby

rvm:
  - 2.4.0
  - 2.3.0
  - 2.2.3
  - 2.1.7
  - 2.0.0
  - rbx-2
  - jruby-9.0.5.0
  - jruby-head
  - ruby-head
  - ext-truffleruby

matrix:
  include:
    - rvm: 2.3.1
      before_script:
        - bundle exec danger
      after_script:
        - bundle exec codeclimate-test-reporter
    - rvm: 2.3.1
      install:
        - for dir in spec/integration/*; do BUNDLE_GEMFILE=$dir/Gemfile bundle; done
      script:
        - set -e ; for dir in spec/integration/*; do BUNDLE_GEMFILE=$dir/Gemfile bundle exec rspec $dir; done
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
